DATASET:
  #TRAIN: "/home/qiuqiu/Desktop/coco2017/train2017.txt"
  #VAL: "/home/qiuqiu/Desktop/coco2017/val2017.txt"
  #NAMES: "configs/coco.names"
  TRAIN: "/content/YoloDataset/train.txt"
  VAL: "/content/YoloDataset/val.txt"
  NAMES: "/content/YoloDataset/category.names"
MODEL:
  NC: 5
  INPUT_WIDTH: 352
  INPUT_HEIGHT: 352
TRAIN:
  LR: 0.001
  THRESH: 0.25
  WARMUP: true
  BATCH_SIZE: 96
  END_EPOCH: 300
  MILESTIONES:
    - 100
    - 200
    - 250
